name: Deploy - EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${ { secrets.HOST_DNS }}
        REMOTE_USER: ${ { secrets.USERNAME }}
        TARGET: ${ { secrets.TARGET_DIR }}
    - name: Deploy to Server 1 
      run: |
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}

